version: "3.7"
services:
  mysql-development:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminpwd
      MYSQL_DATABASE: jogging-tracker
  mysql-test:
    image: mysql:8.0.30
    restart: always
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminpwd
      MYSQL_DATABASE: jogging-tracker-test