/**
 * The key name in the config file representing the secret key to be used by Jwt to sign the bearer token.
 */
export const JWT_SECRET_CONFIG_KEY = 'JWT_SECRET';

/**
 * The key name in the config file representing the expiration time of the bearer token generated by Jwt.
 */
export const JWT_TOKEN_EXPIRATION_CONFIG_KEY = 'JWT_EXPIRES_IN';
