/**
 * The key name in the config file representing the secret key to be used by Jwt to generate the invite token.
 */
export const JWT_SECRET_CONFIG_KEY = 'INVITE_JWT_SECRET';

/**
 * The key name in the config file representing the expiration time of the invite token generated by Jwt
 */
export const JWT_TOKEN_EXPIRATION_CONFIG_KEY = 'INVITE_JWT_EXPIRES_IN';
