export const DEFAULT_MAIL_SENDER_ADDRESS = 'DEFAULT_MAIL_SENDER_ADDRESS';
export const INVITATION_MAIL_TEMPLATE_ID = 'INVITATION_MAIL_TEMPLATE_ID';
export const ACCOUNT_VALIDATION_MAIL_TEMPLATE_ID = 'ACCOUNT_VALIDATION_MAIL_TEMPLATE_ID';
